# Generated by Django 5.0.1 on 2024-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instprofile',
            name='followers_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
