# Generated by Django 4.2.9 on 2024-01-18 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inst_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
