# Generated by Django 5.0.1 on 2024-01-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_profiles', '0002_alter_instprofile_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instprofile',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='instprofile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
